# Generated by Django 4.2.20 on 2025-09-01 15:34

import apps.products.utils.generate_image_path
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Selected')),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Sale Price')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barcode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Discount')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('currency_type', models.CharField(choices=[('usd', 'USD'), ('uzs', 'UZS')], max_length=3)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=apps.products.utils.generate_image_path.product_image_upload_path, verbose_name='Product Image')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ReportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.reportoption', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product', verbose_name='Product')),
                ('report_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.reportoption', verbose_name='Report')),
            ],
        ),
    ]
