# Generated by Django 4.2.20 on 2025-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Sale Price'),
        ),
    ]
