# Generated by Django 4.2.20 on 2025-09-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_category_remove_shopcategory_shop_and_more'),
        ('products', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.category', verbose_name='Category'),
        ),
    ]
