# Generated by Django 4.2.20 on 2026-03-01 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_productgroup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('image', models.ImageField(default='shop-category-images/default-image.png', upload_to='shop-category-images/', verbose_name='Image')),
                ('can_delete', models.BooleanField(default=True)),
                ('shops', models.ManyToManyField(blank=True, related_name='categories', to='shops.shop', verbose_name='Shops')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category'),
        ),
    ]
