# Generated by Django 4.2.20 on 2026-03-01 03:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=50, verbose_name='Discount'),
        ),
    ]
