# Generated by Django 4.2.20 on 2025-09-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Discount')),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Agreed Price')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Paid Amount')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Debt')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=28, verbose_name='Profit')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cancelled_by_admin', 'Cancelled by Admin')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=20, verbose_name='Payment Method')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
            ],
        ),
    ]
