# Generated by Django 4.2.20 on 2025-09-25 12:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_debt_remove_order_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payed', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=60)),
                ('un_payed', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=60)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
