# Generated by Django 4.2.20 on 2025-10-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderpaymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentdetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='orders.order', verbose_name='Order'),
        ),
    ]
