# Generated by Django 4.2.20 on 2025-10-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderpaymentdetail_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=60)),
                ('income_price', models.DecimalField(decimal_places=5, max_digits=60)),
                ('currency_rate_value', models.DecimalField(blank=True, decimal_places=5, max_digits=60, null=True)),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='orders.orderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
