# Generated by Django 4.2.20 on 2026-03-02 14:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currency_rate', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50)),
                ('transaction_type', models.CharField(blank=True, choices=[('debt', 'Debt'), ('payment', 'Payment')], max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
