# Generated by Django 4.2.20 on 2025-09-02 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('shops', '0002_initial'),
        ('promocodes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Cart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
