# Generated by Django 4.2.20 on 2025-09-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_created_at_cart_customer_cart_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
