# Generated by Django 4.2.20 on 2025-08-16 17:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('income_price', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('profit_as_percent', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency_rate_value', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product Part',
                'verbose_name_plural': 'Product Parts',
            },
        ),
    ]
