# Generated by Django 4.2.20 on 2025-08-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_debtpaymenthistory_amount_and_more'),
        ('product_part', '0003_alter_productpart_currency_rate_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpart',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parts', to='supplier.supplier'),
        ),
    ]
