# Generated by Django 4.2.20 on 2026-03-02 14:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.0'), max_digits=30, null=True, verbose_name='Salary')),
                ('role', models.CharField(blank=True, choices=[('cashier_admin', 'CASHIER_ADMIN'), ('owner', 'OWNER'), ('main_admin', 'MAIN_ADMIN')], max_length=20, null=True, verbose_name='Role')),
                ('total_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Total Approved Orders Commission (%)')),
                ('admin_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Admin Approved Orders Commission (%)')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
