# Generated by Django 4.2.20 on 2025-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('role', models.CharField(choices=[('cashier_admin', 'CASHIER_ADMIN'), ('owner', 'OWNER'), ('main_admin', 'MAIN_ADMIN')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
