# Generated by Django 4.2.20 on 2026-01-26 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.0'), max_digits=30, null=True, verbose_name='Salary'),
        ),
    ]
