# Generated by Django 4.2.20 on 2025-10-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='admin_approved_orders_commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Admin Approved Orders Commission (%)'),
        ),
        migrations.AddField(
            model_name='role',
            name='total_approved_orders_commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Approved Orders Commission (%)'),
        ),
    ]
