# Generated by Django 4.2.20 on 2025-08-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0002_role_delete_roleuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
    ]
