# Generated by Django 4.2.20 on 2025-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0003_alter_role_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('cashier_admin', 'CASHIER_ADMIN'), ('owner', 'OWNER'), ('main_admin', 'MAIN_ADMIN')], max_length=20),
        ),
    ]
