# Generated by Django 4.2.20 on 2025-10-05 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0005_alter_category_shops'),
        ('role_manager', '0003_role_admin_approved_orders_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
