# Generated by Django 4.2.20 on 2026-01-31 14:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0003_alter_role_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='admin_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Admin Approved Orders Commission (%)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='total_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Total Approved Orders Commission (%)'),
        ),
    ]
