# Generated by Django 4.2.20 on 2025-10-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0005_alter_role_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='admin_approved_orders_commission_percentage',
            new_name='admin_commission_percent',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='total_approved_orders_commission_percentage',
            new_name='total_commission_percent',
        ),
    ]
