# Generated by Django 4.2.20 on 2025-11-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0006_rename_admin_approved_orders_commission_percentage_role_admin_commission_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='role_manager.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
