# Generated by Django 4.2.20 on 2025-11-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0007_salarytransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryTransaction',
        ),
    ]
