# Generated by Django 4.2.20 on 2025-09-01 15:34

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chief admin', 'Chief admin'), ('cash admin', 'Cash admin')], max_length=64, verbose_name='Admin Type')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Salary')),
                ('total_approved_orders_commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Approved Orders Commission (%)')),
                ('admin_approved_orders_commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Admin Approved Orders Commission (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('link', models.CharField(default=common.utils.generate_unique_text, max_length=32, unique=True, verbose_name='Link')),
                ('image', models.ImageField(upload_to='shop-images/%Y/', verbose_name='Image')),
                ('address', models.TextField(verbose_name='Address')),
                ('latitude', models.CharField(max_length=200, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=200, verbose_name='Longitude')),
                ('telegram_link', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telegram link')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'permissions': [('add_product', 'Add product'), ('change_product', 'Update product'), ('delete_product', 'Delete product'), ('add_category', 'Add category'), ('change_category', 'Update category'), ('delete_category', 'Delete category'), ('confirm_order', 'Confirm order'), ('cancel_order', 'Cancel order')],
            },
        ),
        migrations.CreateModel(
            name='ShopBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profit', models.DecimalField(decimal_places=5, max_digits=50)),
                ('cash', models.DecimalField(decimal_places=5, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('cash_income', 'Cash_Income'), ('cash_outcome', 'Cash_Outcome'), ('profit', 'Profit'), ('loss', 'Loss'), ('cash_profit', 'Cash_Profit'), ('cash_loss', 'Cash_Loss')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('note', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Full name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('image', models.ImageField(default='shop-category-images/default-image.png', upload_to='shop-category-images/', verbose_name='Image')),
                ('can_delete', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Shop Category',
                'verbose_name_plural': 'Shop Categories',
            },
        ),
    ]
