# Generated by Django 4.2.20 on 2025-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('image', models.ImageField(default='shop-category-images/default-image.png', upload_to='shop-category-images/', verbose_name='Image')),
                ('can_delete', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='user',
        ),
    ]
