# Generated by Django 4.2.20 on 2026-01-26 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbalance',
            name='cash',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='shopbalance',
            name='profit',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50),
        ),
    ]
