# Generated by Django 4.2.20 on 2025-09-17 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_product_category'),
        ('shops', '0003_category_remove_shopcategory_shop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='shops.shop', verbose_name='Shops'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
