# Generated by Django 4.2.20 on 2026-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shopbalance_cash_alter_shopbalance_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
