# Generated by Django 4.2.20 on 2025-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_delete_shopcategory_category_shops_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='categories', to='shops.shop', verbose_name='Shops'),
        ),
    ]
