# Generated by Django 4.2.20 on 2025-10-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_category_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
    ]
