# Generated by Django 4.2.20 on 2026-02-24 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
