# Generated by Django 4.2.20 on 2026-03-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alter_product_category'),
        ('shops', '0007_alter_shop_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
