# Generated by Django 4.2.20 on 2025-08-09 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_roleuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.CharField(choices=[('cashier_admin', 'CASHIER_ADMIN'), ('owner', 'OWNER'), ('main_admin', 'MAIN_ADMIN')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
