# Generated by Django 4.2.20 on 2025-08-09 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_roleuser_role_alter_roleuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
