# Generated by Django 4.2.20 on 2025-08-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_roleuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
