# Generated by Django 4.2.20 on 2025-08-30 07:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('income_price', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('profit_as_percent', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency_rate_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentItemBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('income_price', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('profit_as_percent', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency_rate_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('promo_code_value', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('payed_money', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('un_payed_money', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency_type', models.CharField(choices=[('usd', 'USD'), ('uzs', 'UZS')], max_length=10)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_info', to='document.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
