# Generated by Django 4.2.20 on 2025-08-07 18:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='income_price',
            field=models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='profit_as_percent',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='qty',
            field=models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='income_price',
            field=models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='profit_as_percent',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='qty',
            field=models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='sale_price',
            field=models.DecimalField(decimal_places=5, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
