# Generated by Django 4.2.20 on 2025-08-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitembalance',
            name='document_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='document.documentitem'),
        ),
    ]
