# Generated by Django 4.2.20 on 2025-12-18 12:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='profit_as_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='profit_as_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
