# Generated by Django 4.2.20 on 2025-08-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to='document.document'),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='document_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='document.documentitem'),
        ),
    ]
