# Generated by Django 4.2.20 on 2025-12-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_address'),
        ('document', '0004_alter_documentitem_profit_as_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='shops.shop'),
        ),
    ]
