# Generated by Django 4.2.20 on 2025-08-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('document', '0004_alter_documentitem_income_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
