# Generated by Django 4.2.20 on 2025-09-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_transaction_delete_debtpaymenthistory'),
        ('document', '0004_documentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='supplier.supplier'),
        ),
    ]
