# Generated by Django 4.2.20 on 2026-01-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_document_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='document.document'),
        ),
    ]
