# Generated by Django 4.2.20 on 2025-10-05 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_document_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetail",
            name="promo_code_value",
            field=models.DecimalField(
                decimal_places=5, default=Decimal("0.0"), max_digits=15
            ),
        ),
    ]
