# Generated by Django 4.2.20 on 2026-01-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shopbalance_cash_alter_shopbalance_profit'),
        ('document', '0006_alter_paymentinfo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shops.shop'),
        ),
    ]
