# Generated by Django 4.2.20 on 2025-10-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_paymentdetail_promo_code_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitembalance',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
        migrations.AlterField(
            model_name='documentitembalance',
            name='document_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='document.documentitem'),
        ),
    ]
