# Generated by Django 4.2.20 on 2026-02-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_initial'),
        ('document', '0007_alter_document_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='supplier.supplier'),
        ),
    ]
