# Generated by Django 4.2.20 on 2025-12-18 12:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_money', models.DecimalField(decimal_places=5, max_digits=60)),
                ('remained_money', models.DecimalField(decimal_places=5, max_digits=60)),
                ('currency_type', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDebtBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance_usd', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50)),
                ('balance_uzs', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currency_type', models.CharField(max_length=10)),
                ('currency_rate', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50)),
                ('transaction_type', models.CharField(blank=True, choices=[('debt', 'Debt'), ('payment', 'Payment')], max_length=250, null=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='supplier.supplierdebtbalance')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
