# Generated by Django 4.2.20 on 2026-03-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_initial'),
        ('supplier', '0001_initial'),
        ('document', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='supplierdebtbalance',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_balance', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shops',
            field=models.ManyToManyField(related_name='suppliers', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='debt_purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.debtpurchase'),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliertransaction'),
        ),
        migrations.AddField(
            model_name='debtpurchase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_purchases_as_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtpurchase',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_purchase', to='document.document'),
        ),
        migrations.AddField(
            model_name='debtpurchase',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='debtpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_purchases_as_supplier', to='supplier.supplier'),
        ),
    ]
