# Generated by Django 4.2.20 on 2025-08-07 17:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtpaymenthistory',
            old_name='value',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='debtpaymenthistory',
            name='currency_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=15),
        ),
    ]
