# Generated by Django 4.2.20 on 2025-08-07 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_value_debtpaymenthistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtpaymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
        migrations.AlterField(
            model_name='debtpaymenthistory',
            name='currency_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='supplierdebtbalance',
            name='balance_usd',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='supplierdebtbalance',
            name='balance_uzs',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=50),
        ),
    ]
