# Generated by Django 4.2.20 on 2025-10-15 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_remove_shop_owner'),
        ('document', '0006_alter_paymentdetail_promo_code_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0004_suppliertransaction_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_money', models.DecimalField(decimal_places=5, max_digits=60)),
                ('remained_money', models.DecimalField(decimal_places=5, max_digits=60)),
                ('currency_type', models.CharField(max_length=6)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_purchases_as_creator', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_purchase', to='document.document')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_purchases_as_supplier', to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('debt_purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.debtpurchase')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliertransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
