# Generated by Django 4.2.20 on 2025-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('reverted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', 'So‘m'), ('USD', 'Dollar')], default='UZS', max_length=3)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
