# Generated by Django 4.2.20 on 2026-03-18 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
        ('document', '0002_initial'),
        ('debt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtconversion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_conversions', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='debtconversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
        migrations.AddField(
            model_name='debt',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='shops.shop'),
        ),
    ]
