# Generated by Django 4.2.20 on 2025-08-03 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtconversion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_conversions', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='debtconversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_conversions', to=settings.AUTH_USER_MODEL),
        ),
    ]
