# Generated by Django 4.2.20 on 2025-08-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
