# Generated by Django 4.2.20 on 2025-08-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        ('document', '0003_initial'),
        ('debt', '0005_debt_is_accepted_debt_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document.document'),
        ),
    ]
