# Generated by Django 4.2.20 on 2025-08-16 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_initial'),
        ('debt', '0006_debt_shop_alter_debt_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='document.document'),
        ),
    ]
