# Generated by Django 4.2.20 on 2026-03-18 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='promocodeitem',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promocodes.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocode_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeitem',
            unique_together={('promo_code', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together={('shop', 'code')},
        ),
    ]
