# Generated by Django 4.2.20 on 2025-08-03 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('shops', '0001_initial'),
        ('promocodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='promocodeitem',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promocodes.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to='products.product'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeitem',
            unique_together={('promocode', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together={('shop', 'code')},
        ),
    ]
