# Generated by Django 4.2.20 on 2026-03-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promocodes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocodeitem',
            old_name='promocode',
            new_name='promo_code',
        ),
        migrations.RenameField(
            model_name='promocodeusage',
            old_name='promocode',
            new_name='promo_code',
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocode_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeitem',
            unique_together={('promo_code', 'product')},
        ),
    ]
