# Generated by Django 4.2.20 on 2025-08-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_initial'),
        ('promocodes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_promocodes', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promocodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
