# Generated by Django 4.2.20 on 2025-08-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0003_alter_promocode_shop_alter_promocode_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
    ]
