# Generated by Django 4.2.20 on 2025-08-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        ('promocodes', '0004_alter_promocode_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together={('shop', 'code')},
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='value',
        ),
    ]
