# Generated by Django 4.2.20 on 2025-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rate', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
    ]
