# Generated by Django 4.2.20 on 2025-12-18 12:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Balance')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
