# Generated by Django 4.2.20 on 2026-03-02 14:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=25, verbose_name='Balance')),
                ('personal_salary', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=25, null=True, verbose_name='Personal Salary')),
                ('global_salary', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=25, null=True, verbose_name='Global Salary')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
