# Generated by Django 4.2.20 on 2026-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('admin_panel', '0001_initial'),
        ('role_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarybalance',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_as_salary', to='role_manager.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='percentagetracker',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.document', verbose_name='Document'),
        ),
    ]
