# Generated by Django 4.2.20 on 2025-12-18 13:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarybalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=25, verbose_name='Balance'),
        ),
    ]
