# Generated by Django 4.2.20 on 2025-12-26 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_salarybalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarybalance',
            name='global_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=25, null=True, verbose_name='Global Salary'),
        ),
        migrations.AddField(
            model_name='salarybalance',
            name='personal_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=25, null=True, verbose_name='Personal Salary'),
        ),
    ]
