# Generated by Django 4.2.20 on 2025-12-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0002_initial'),
        ('admin_panel', '0004_salarybalance_global_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarybalance',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_as_salary', to='role_manager.role', verbose_name='Role'),
        ),
    ]
