# Generated by Django 4.2.20 on 2026-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('status', models.CharField(choices=[('YANGI', 'Yangi'), ('ESKI', 'Eski')], max_length=128, verbose_name='Status')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('address', models.TextField(verbose_name='Address')),
                ('latitude', models.CharField(max_length=256, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=256, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('image', models.ImageField(default='category-images/default.jpg', upload_to='category-images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Advertisement Category',
                'verbose_name_plural': 'Advertisement Categories',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisement-images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.advertisement', verbose_name='Advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Image',
                'verbose_name_plural': 'Advertisement Images',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertisements.advertisementcategory', verbose_name='Category'),
        ),
    ]
