# Generated by Django 4.2.20 on 2025-08-11 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_session', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
