# Generated by Django 4.2.20 on 2025-08-30 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Cash History',
                'verbose_name_plural': 'Cash Histories',
            },
        ),
        migrations.CreateModel(
            name='CashHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('cash_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_history_item', to='cash.cashhistory', verbose_name='Cash History')),
            ],
            options={
                'verbose_name': 'Cash History Item',
                'verbose_name_plural': 'Cash History Items',
            },
        ),
    ]
