# Generated by Django 4.2.20 on 2026-03-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('cash', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhistory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_history', to='shops.shop', verbose_name='Shop'),
        ),
    ]
