# Generated by Django 4.2.20 on 2026-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
