name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main # Deploy faqat main branch'ga push qilinganda ishga tushadi

  workflow_dispatch: # Qo'lda ishga tushirish uchun

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pythonanywhereapiclient

      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_API_CLIENT_HOST: ${{ vars.PYTHONANYWHERE_HOST }}
          PYTHONANYWHERE_API_CLIENT_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          PYTHONANYWHERE_API_CLIENT_USER: ${{ secrets.PYTHONANYWHERE_USER }}
          PYTHONANYWHERE_WORKING_DIRECTORY: ${{ secrets.PYTHONANYWHERE_WORKING_DIRECTORY }}
          PYTHONANYWHERE_DOMAIN_NAME: ${{ vars.PYTHONANYWHERE_DOMAIN }}
        run: |
          python deploy.py
