# Generated by Django 4.2.20 on 2026-03-04 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameuserbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuserbalance',
            name='season_item',
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('season_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameuserbalance')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
