# Generated by Django 4.2.20 on 2026-03-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gameuserbalance_season_item_gameitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='game_balance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.gameuserbalance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='season_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.seasonitem'),
        ),
    ]
