# Generated by Django 4.2.20 on 2026-03-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameitem_game_balance_alter_gameitem_season_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
