# Generated by Django 4.2.20 on 2026-03-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_season_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='limit',
            new_name='limit_price',
        ),
    ]
