# Generated by Django 4.2.20 on 2026-03-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_limit_season_limit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
