# Generated by Django 4.2.20 on 2026-03-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_season_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
