# Generated by Django 4.2.20 on 2026-03-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_season_limit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='has_debt',
            field=models.BooleanField(default=False),
        ),
    ]
